# LocalConfig fields
location = "local-2"
server_id = 2
listen_address = "0.0.0.0"
listen_port = 8002
num_clients = 1
output_filepath = "./logs/server-2.json"

# ClusterConfig fields
nodes = [1, 2, 3]
node_addrs = ["127.0.0.1:8001", "127.0.0.1:8002", "127.0.0.1:8003"]
initial_leader = 1