# LocalConfig fields
location = "local-3"
server_id = 3
listen_address = "0.0.0.0"
listen_port = 8003
num_clients = 0
output_filepath = "./logs/server-3.json"

# ClusterConfig fields
nodes = [1, 2, 3]
node_addrs = ["127.0.0.1:8001", "127.0.0.1:8002", "127.0.0.1:8003"]
initial_leader = 1